### ISSUE TITLE
Still loads empty TableView

### ISSUE THREAD

**Issue by serkanerkan** [ole/AppointmentList#1]
I have testing on my device. But this example is loading empty TableView.. How can i access my calendar? Thanks.

**Comment by ole** [comment]
I suspect the problem is that on iOS 6 and later, accessing the event store requires user authorization. This demo app was written for iOS 5 and therefore doesn't call the now required `-[EKEventStore requestAccessToEntityType:completion:]` method to prompt the user for authorization.

I will not update the code myself, sorry. But if you decide to do it yourself, please send a pull request.
